name: climatematch
channels:
 - conda-forge
 - nodefaults
dependencies:
 # - python=3.9
 - adlfs
 - argopy
 - awscli
 - boto3
 - bottleneck
 - cartopy
 - cdsapi
 - cfgrib
 - ciso  # no build for osx-arm64
 - climlab
 - cmocean
 - dask-ml
 - datashader
 - descartes
 - earthaccess
 - ecco_v4_py  # no build for osx-arm64
#  - eigen # needed for SDFC
 - eofs
 - erddapy
 - esmf
 - esmpy
 - fastjmd95
 - flox
 - fsspec
 - gcm_filters
 - gcsfs
 - gh
 - geocube
 - geopandas
 - geopy
 - geoviews-core
 - gh-scoped-creds
 - git
 - git-lfs
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipykernel>=6.21.2
 - ipyleaflet
 - ipytree
 - ipywidgets
 - jupyter-panel-proxy
 - jupyter-resource-usage
 - jupyterlab-git
 - kerchunk
 - lxml
 - lz4
 - matplotlib-base
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - nltk
 - numcodecs
 - numpy
 - odc-stac
 - openpyxl
 - pandas
 - panel
 - parcels
 - param
 - pip
 - plotly
 - pooch
 - pop-tools
 - pyarrow
#  - pybind11 # needed for SDFC
 - pycamhd
 - pydap
 - pygeos
 - pystac
 - pystac-client
 - pythia-datasets
 - python-blosc
 - python-gist
 - python-graphviz
 - pyworld3 # needed for W2D3
 - rasterio
 - rechunker
 - rio-cogeo
 - rioxarray
 - s3fs
 - satpy
 - scikit-image
 - scikit-learn
 - scipy<=1.11.4 # for pyleoclim
 - seaborn
 - sparse
 - snakeviz
 - stackstac
 - texttable
 - tiledb-py
 - timezonefinder
 - torch
 - wordcloud
 - xarray==2024.2.0
 - xarrayutils
 - xarray-datatree
 - xarray_leaflet
 - xarray-spatial
 - xbatcher
 - xclim
 - xesmf
 - xgcm
 - xhistogram
 - xmip
 - xmitgcm
 - xpublish
 - xrft
 - xskillscore
 - zarr
 - pip:
   - afinn
   - lipd
   - pyleoclim
   - "mystatsfunctions @ https://github.com/njleach/mystatsfunctions/archive/main.zip"
#   - "SDFC @ https://github.com/yrobink/SDFC/archive/master.zip" # this is not working
#   -  https://github.com/mptouzel/PyDICE/archive/master.zip # for W2D3 Tutorial 2

